//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjNewJQGrid5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MainDbContext : DbContext
    {
        public MainDbContext()
            : base("name=MainDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersNew> UsersNews { get; set; }
    
        public virtual int CreateUser(string nEmailId, string nPassword, string nPasswordSalt)
        {
            var nEmailIdParameter = nEmailId != null ?
                new ObjectParameter("NEmailId", nEmailId) :
                new ObjectParameter("NEmailId", typeof(string));
    
            var nPasswordParameter = nPassword != null ?
                new ObjectParameter("NPassword", nPassword) :
                new ObjectParameter("NPassword", typeof(string));
    
            var nPasswordSaltParameter = nPasswordSalt != null ?
                new ObjectParameter("NPasswordSalt", nPasswordSalt) :
                new ObjectParameter("NPasswordSalt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateUser", nEmailIdParameter, nPasswordParameter, nPasswordSaltParameter);
        }
    
        public virtual int DeleteUser(string nEmailId)
        {
            var nEmailIdParameter = nEmailId != null ?
                new ObjectParameter("NEmailId", nEmailId) :
                new ObjectParameter("NEmailId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUser", nEmailIdParameter);
        }
    
        public virtual int UpdateUser(string nEmailId, string nPassword, string nPasswordSalt)
        {
            var nEmailIdParameter = nEmailId != null ?
                new ObjectParameter("NEmailId", nEmailId) :
                new ObjectParameter("NEmailId", typeof(string));
    
            var nPasswordParameter = nPassword != null ?
                new ObjectParameter("NPassword", nPassword) :
                new ObjectParameter("NPassword", typeof(string));
    
            var nPasswordSaltParameter = nPasswordSalt != null ?
                new ObjectParameter("NPasswordSalt", nPasswordSalt) :
                new ObjectParameter("NPasswordSalt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUser", nEmailIdParameter, nPasswordParameter, nPasswordSaltParameter);
        }
    
        public virtual int NCreateUser(string nEmailId, string nPassword, string nPasswordSalt, byte[] nImage)
        {
            var nEmailIdParameter = nEmailId != null ?
                new ObjectParameter("NEmailId", nEmailId) :
                new ObjectParameter("NEmailId", typeof(string));
    
            var nPasswordParameter = nPassword != null ?
                new ObjectParameter("NPassword", nPassword) :
                new ObjectParameter("NPassword", typeof(string));
    
            var nPasswordSaltParameter = nPasswordSalt != null ?
                new ObjectParameter("NPasswordSalt", nPasswordSalt) :
                new ObjectParameter("NPasswordSalt", typeof(string));
    
            var nImageParameter = nImage != null ?
                new ObjectParameter("NImage", nImage) :
                new ObjectParameter("NImage", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NCreateUser", nEmailIdParameter, nPasswordParameter, nPasswordSaltParameter, nImageParameter);
        }
    
        public virtual int NDeleteUser(string nEmailId)
        {
            var nEmailIdParameter = nEmailId != null ?
                new ObjectParameter("NEmailId", nEmailId) :
                new ObjectParameter("NEmailId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NDeleteUser", nEmailIdParameter);
        }
    
        public virtual int NUpdateUser(string nEmailId, string nPassword, string nPasswordSalt, byte[] nImage)
        {
            var nEmailIdParameter = nEmailId != null ?
                new ObjectParameter("NEmailId", nEmailId) :
                new ObjectParameter("NEmailId", typeof(string));
    
            var nPasswordParameter = nPassword != null ?
                new ObjectParameter("NPassword", nPassword) :
                new ObjectParameter("NPassword", typeof(string));
    
            var nPasswordSaltParameter = nPasswordSalt != null ?
                new ObjectParameter("NPasswordSalt", nPasswordSalt) :
                new ObjectParameter("NPasswordSalt", typeof(string));
    
            var nImageParameter = nImage != null ?
                new ObjectParameter("NImage", nImage) :
                new ObjectParameter("NImage", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NUpdateUser", nEmailIdParameter, nPasswordParameter, nPasswordSaltParameter, nImageParameter);
        }
    }
}
